_BASE_: ../maskformer2_R50_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "pretrained_weights/swin_large_patch4_window12_384_22k.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RANKSEG:
    FLAG: True
    LOSS_WEIGHT: 10
    TOPK: 150
  SEM_SEG_HEAD:
    USE_LAYERNORM: True
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
SOLVER:
  MLHEAD_MULTIPLIER: 0.1
TEST:
  EVAL_PERIOD: 10000

