_BASE_: video_maskformer2_R50_bs16_8ep.yaml
MODEL:
  WEIGHTS: "pretrained_weights/model_final_eba159.pkl"
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
  RANKSEG:
    FLAG: True
    LOSS_WEIGHT: 10
    TOPK: 124
  SEM_SEG_HEAD:
    USE_LAYERNORM: True
SOLVER:
  MLHEAD_MULTIPLIER: 2.0

